import os,json
b=r"D:/Fishing project/miniprogram/pages"
data={
"equip":["<view class=\"page\"><view class=\"card\"><scroll-view scroll-x style=\"white-space:nowrap;margin-bottom:16rpx;\"><text wx:for=\"{{types}}\" wx:key=\"*this\" data-type=\"{{item}}\" bindtap=\"switchType\" style=\"display:inline-block;padding:10rpx 20rpx;border-radius:20rpx;font-size:24rpx;margin-right:8rpx;{{curType===item?\"background:var(--primary);color:white;\":\"border:2rpx solid var(--border);color:var(--text-secondary);\"}}\">{{item}}</text></scroll-view><view style=\"font-weight:600;color:var(--danger);margin:12rpx 0 8rpx;\">MUST</view><view wx:for=\"{{data.must}}\" wx:key=\"*this\" style=\"padding:8rpx 0;font-size:26rpx;\">{{item}}</view><view style=\"font-weight:600;color:var(--warning);margin:12rpx 0 8rpx;\">REC</view><view wx:for=\"{{data.rec}}\" wx:key=\"*this\" style=\"padding:8rpx 0;font-size:26rpx;\">{{item}}</view><view style=\"font-weight:600;color:var(--text-light);margin:12rpx 0 8rpx;\">OPT</view><view wx:for=\"{{data.opt}}\" wx:key=\"*this\" style=\"padding:8rpx 0;font-size:26rpx;\">{{item}}</view></view></view>"],
"wiki":["<view class=\"page\" style=\"padding:0 20rpx;\"><block wx:for=\"{{list}}\" wx:key=\"name\"><view class=\"card\" style=\"margin-bottom:8rpx;display:flex;align-items:center;gap:16rpx;\" bindtap=\"showDetail\" data-idx=\"{{index}}\"><text style=\"font-size:44rpx;\">{{item.icon}}</text><view style=\"flex:1;\"><view style=\"font-weight:600;\">{{item.name}}</view><view style=\"font-size:22rpx;color:var(--text-light);\">{{item.alias}}</view></view><text style=\"color:var(--text-light);\">&gt;</text></view></block><view wx:if=\"{{sel}}\" style=\"position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.5);z-index:200;display:flex;align-items:flex-end;\"><view style=\"background:white;width:100%;border-radius:32rpx 32rpx 0 0;padding:32rpx;max-height:80vh;overflow-y:auto;\"><text style=\"text-align:center;font-size:64rpx;display:block;\">{{sel.icon}}</text><view style=\"text-align:center;font-size:36rpx;font-weight:700;margin:8rpx 0;\">{{sel.name}}</view><view style=\"text-align:center;font-size:24rpx;color:var(--text-light);margin-bottom:16rpx;\">{{sel.alias}}</view><view style=\"background:var(--bg);padding:20rpx;border-radius:8rpx;margin-bottom:12rpx;display:grid;grid-template-columns:1fr 1fr;gap:8rpx;font-size:24rpx;color:var(--text-secondary);\"><view>{{sel.temp}}</view><view>{{sel.depth}}</view><view>{{sel.time}}</view><view>{{sel.season}}</view></view><view style=\"font-size:24rpx;color:var(--text-secondary);margin:8rpx 0;\">{{sel.methods}}</view><view style=\"font-size:24rpx;color:var(--text-secondary);margin:8rpx 0;\">{{sel.taste}}</view><view style=\"font-size:24rpx;color:var(--text-light);margin-bottom:16rpx;\">{{sel.desc}}</view><button class=\"btn btn-primary\" bindtap=\"closeDetail\">Close</button></view></view></view>"],
"market":["<view class=\"page\" style=\"padding:0 20rpx;\"><block wx:for=\"{{items}}\" wx:key=\"id\"><view class=\"card\" style=\"margin-bottom:12rpx;\"><view style=\"font-weight:600;font-size:30rpx;\">{{item.fishName}} {{item.weight}}</view><view style=\"font-size:24rpx;color:var(--text-light);margin-top:4rpx;\">{{item.date}} | {{item.port}}</view><view style=\"margin-top:8rpx;display:flex;gap:16rpx;align-items:center;\"><text style=\"font-size:28rpx;color:var(--danger);font-weight:600;\">{{item.price}}</text><text style=\"font-size:24rpx;color:var(--text-secondary);\">{{item.takeMethod}}</text></view><button class=\"btn btn-outline btn-sm\" style=\"margin-top:12rpx;width:100%;\" bindtap=\"contact\" data-id=\"{{item.id}}\">Contact Seller</button></view></block><view wx:if=\"{{items.length===0}}\" class=\"empty\"><view class=\"empty-text\">No items for sale</view></view></view>"],
"guide":["<view class=\"page\" style=\"padding:0 20rpx;\"><view style=\"display:flex;gap:8rpx;margin-bottom:16rpx;\"><view wx:for=\"{{tabs}}\" wx:key=\"*this\" data-tab=\"{{item}}\" bindtap=\"switchTab\" style=\"flex:1;text-align:center;padding:16rpx;border-radius:12rpx;font-size:26rpx;{{curTab===item?\"background:var(--primary);color:white;\":\"background:white;color:var(--text-secondary);border:2rpx solid var(--border);\"}}\">{{item}}</view></view><view wx:if=\"{{curTab===tabs[0]}}\" class=\"card\"><view style=\"font-size:26rpx;line-height:1.8;\"><view style=\"font-weight:600;color:var(--danger);\">Take 30-60min before boarding</view><view style=\"font-weight:600;margin-top:12rpx;\">Recommended</view><view>Travelmin 30-50 | Dramamine 5-10 | Scopolamine patch 80-120</view><view style=\"font-weight:600;margin-top:12rpx;\">Tips</view><view>Ginger slice | Sleep well | Look far | Sit middle | Not too full/empty</view><view style=\"color:var(--danger);margin-top:12rpx;\">Severe vomiting: return to shore immediately</view></view></view><view wx:if=\"{{curTab===tabs[1]}}\" class=\"card\"><view style=\"font-size:26rpx;line-height:1.8;\"><view style=\"font-weight:600;\">1. Bleed</view><view>Cut gills immediately. Makes meat whiter, fresher. Must for large fish.</view><view style=\"font-weight:600;margin-top:12rpx;\">2. Vent</view><view>Deep water fish bladder expands. Needle behind pectoral fin.</view><view style=\"font-weight:600;margin-top:12rpx;\">3. Ice</view><view>Rinse with seawater. 1:1 ice to fish ratio.</view><view style=\"font-weight:600;margin-top:12rpx;\">4. Transport</view><view>No live fish on train/plane. Use car fridge.</view><view style=\"background:#ECFDF5;padding:12rpx;border-radius:8rpx;margin-top:12rpx;color:#065F46;font-weight:600;\">Bleed, vent, ice, go home fast</view></view></view></view>"],
"gear":["<view class=\"page\" style=\"padding:0 20rpx;\"><view style=\"display:flex;gap:8rpx;margin-bottom:16rpx;\"><view wx:for=\"{{tiers}}\" wx:key=\"*this\" data-tier=\"{{item}}\" bindtap=\"switchTier\" style=\"flex:1;text-align:center;padding:16rpx;border-radius:12rpx;font-size:26rpx;{{curTier===item?\"background:var(--primary);color:white;\":\"background:white;color:var(--text-secondary);border:2rpx solid var(--border);\"}}\">{{item}}</view></view><view style=\"font-size:24rpx;color:var(--text-light);margin-bottom:12rpx;\">{{tierInfo.desc}}</view><view wx:for=\"{{tierInfo.items}}\" wx:key=\"name\" style=\"display:flex;justify-content:space-between;padding:12rpx 0;border-bottom:2rpx solid var(--border);font-size:26rpx;\"><view><text style=\"color:var(--primary);\">{{index+1}}.</text> {{item.name}}<view style=\"font-size:22rpx;color:var(--text-light);\">{{item.tip}}</view></view><text style=\"font-weight:600;color:var(--primary);\">{{item.price}}</text></view></view>"],
"moon":["<view class=\"page\" style=\"padding:0 20rpx;\"><view class=\"card\"><view style=\"font-size:32rpx;font-weight:600;text-align:center;margin-bottom:16rpx;\">Moon Calendar</view><view style=\"display:grid;grid-template-columns:repeat(7,1fr);gap:4rpx;text-align:center;\"><view wx:for=\"{{weekDays}}\" wx:key=\"*this\" style=\"font-size:22rpx;color:var(--text-light);padding:8rpx;\">{{item}}</view><view wx:for=\"{{emptyCells}}\" wx:key=\"*this\" style=\"padding:4rpx;\"></view><view wx:for=\"{{days}}\" wx:key=\"day\" style=\"padding:6rpx;border-radius:8rpx;{{item.isToday?\"background:var(--primary);color:white;\":\"\"}}{{item.isSpring?\"border:4rpx solid #F59E0B;\":\"\"}}\"><view style=\"font-size:22rpx;\">{{item.day}}</view><view style=\"font-size:28rpx;\">{{item.icon}}</view><view wx:if=\"{{item.isSpring}}\" style=\"font-size:18rpx;color:#F59E0B;\">Spring</view></view></view><view style=\"font-size:22rpx;color:var(--text-light);text-align:center;margin-top:16rpx;\">Gold = Spring Tide (Full/New Moon)</view></view></view>"]
}
for name, lines in data.items():
    path = b + "/" + name + "/" + name + ".wxml"
    with open(path, "w", encoding="utf-8") as f:
        f.write(lines[0])
    print(name + " done")
print("ALL OK")
